apiVersion: v1
kind: Service
metadata:
  name: nexusai-api
  namespace: nexusai
spec:
  selector:
    app: nexusai-api
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
  type: LoadBalancer
